# Generated by Django 6.0 on 2025-12-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_reminder_created',
            field=models.BooleanField(default=False),
        ),
    ]
